/**
 * This represents all the data stored about a request to be a passenger on a
 * ride which another user has offered
 * 
 * This directly corresponds to the TransitRequestView model on the server
 * 
 * Requests have 2 states:
 * PENDING: (rideID == null) The linked Ride's driver has not approved the Request
 * CONFIRMED: (rideID != null) The linked Ride's driver has approved the Request
 */
class RequestModel {
  constructor(
    requestID,
    requesterUsername,
    rideID,
    requesterNote,
    isConfirmed) {
    
    this.requestID = requestID;
    this.requesterUsername = requesterUsername;
    this.rideID = rideID;
    this.requesterNote = requesterNote;
    this.isConfirmed = isConfirmed;

  }

  /* Declarations */
  requestID; // Primary key of a Request (auto-generated by the database)
  requesterUsername; // The username of the requester
  rideID; // The ID of the Ride that the requester wants to join
  requesterNote; // The requester's note to the Ride's driver (optional)
  isConfirmed; // Whether or not the Request has been approved (0 = Requested; 1 = Confirmed)

}

export default RequestModel;